# Generated by Django 4.1.1 on 2022-10-01 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodOrder',
            new_name='Food_Order',
        ),
    ]
