# Generated by Django 4.1.1 on 2022-10-01 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_foodorder_food_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.order'),
        ),
    ]
