# Generated by Django 4.1.1 on 2022-10-01 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_food_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='user_order',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='user_order',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='food_order',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='food_order',
            name='user_order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user_order'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
    ]
