# Generated by Django 4.1.1 on 2022-10-01 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_food_order_id_remove_food_restaurant_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Food_Order',
            new_name='FoodOrder',
        ),
        migrations.RenameModel(
            old_name='User_Order',
            new_name='UserOrder',
        ),
    ]
